/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.action;

import java.io.File;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DownloadAction;

import com.pwa.common.MessageList;
import com.pwa.data.impoter.ExportDataImporter;
import com.pwa.web.view.ExportDataView;

/**
 * MyEclipse Struts Creation date: 01-04-2552
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class FileDownloadAction extends DownloadAction {
	static Logger log = Logger.getLogger(FileDownloadAction.class);

	@Override
	protected StreamInfo getStreamInfo(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		MessageList msgList = new MessageList();
		String fileName = (String) request.getParameter("fileName");
		ExportDataView exportView = ExportDataImporter.getExportData(fileName, msgList);
		String contentType = "text/plain";
		log.debug("start download file="+fileName);
		String save_file_as = fileName; // the user will see this filename
		response.setHeader("Content-disposition", "attachment; filename=\"" + save_file_as + "\"");
		return new FileStreamInfo(contentType, new File(exportView.getPath()));

	}

//	public static class SI implements StreamInfo {
//
//		private String contentType;
//		private File file;
//
//		public SI(String contentType, File file) {
//			this.contentType = contentType;
//			this.file = file;
//		}
//
//		public String getContentType() {
//			return this.contentType;
//		}
//
//		public InputStream getInputStream() throws IOException {
//			FileInputStream fis = new FileInputStream(file);
//			BufferedInputStream bis = new BufferedInputStream(fis);
//			return bis;
//		}
//	}
}