/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.action;

import java.io.File;
import java.io.FileInputStream;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.pwa.common.MessageList;
import com.pwa.data.impoter.ExportDataImporter;
import com.pwa.web.view.ExportDataView;

/**
 * MyEclipse Struts Creation date: 01-04-2552
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class FileDownloadExportAction extends Action{
	static Logger log = Logger.getLogger(FileDownloadExportAction.class);

	@Override
	   public ActionForward execute(ActionMapping mapping, ActionForm form,
	     HttpServletRequest request, HttpServletResponse response)
	     throws Exception {
		MessageList msgList = new MessageList();
		String fileName = (String) request.getParameter("fileName");
		ExportDataView exportView = ExportDataImporter.getExportData(fileName, msgList);
		String contentType = "text/plain";
		log.debug("start download file="+fileName);
		String save_file_as = fileName; // the user will see this filename
		response.setHeader("Content-Disposition", "attachment; filename=\"" + save_file_as + "\"");
		response.setContentType(contentType);
		ServletOutputStream out =  response.getOutputStream();
		try{
			if(new File(exportView.getPath()).exists()){
				FileInputStream in = new FileInputStream(exportView.getPath());
				byte[] buf = new byte[4 * 1024];  // 4K buffer
				int bytesRead;
				try {
					while ((bytesRead = in.read(buf)) != -1)
					{
						out.write(buf, 0, bytesRead);
					}
					} finally {
						in.close();
				        out.flush();
				        out.close();
					}
			}
	        
	     }catch(Exception e){
	     	e.printStackTrace();
	    }
		 return null;
	}
}