/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.PairValueDesc;
import com.pwa.common.CUtil;
import com.pwa.common.MessageList;
import com.pwa.common.exception.CMException;
import com.pwa.web.ScreenMsgUtil;
import com.pwa.web.helper.WebUtil;
import com.pwa.web.struts.form.HomeForm;

public class HomeAction extends DispatchAction {
	Logger log = Logger.getLogger(HomeAction.class);

	public ActionForward main(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		HttpSession session = request.getSession();
		log.debug("enter ");	
		ArrayList<PairValueDesc> branchList = WebUtil.getBranchList();
		session.setAttribute("branchList", branchList);
		return mapping.findForward("main");
	}

	public ActionForward submit(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		HttpSession session = request.getSession();
		HomeForm f = (HomeForm) form;
		log.debug("enter ");
		MessageList msgList = new MessageList();
		String branch = f.getBranch();
		System.out.print("branch  "+branch);
		try {
			if (CUtil.isBlank(branch)) { // validate
				throw new CMException("E", "กรุณาระบุสาขา");
			}
		} catch (Exception e) {
			msgList.addMessage(e);
		}
		ActionForward forward = null;
		if (!msgList.isContainError()) {
			String branchName = WebUtil.getBranchName(branch);
			System.out.print("values  "+branchName);
			session.setAttribute("br", branch);
			session.setAttribute("head", branchName);
			session.getServletContext().setAttribute("br", branch);
			session.getServletContext().setAttribute("head", branchName);
			forward = mapping.findForward("success");
		} else {
			forward = mapping.findForward("main");
		}

		saveMessages(request, ScreenMsgUtil.getMsgsToScreen(msgList));

		return forward;
	}
}