/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.action;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.text.ParseException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.pwa.common.MessageList;
import com.pwa.data.impoter.MasterImporter;
import com.pwa.web.ScreenMsgUtil;
import com.pwa.web.helper.WebConst;
import com.pwa.web.helper.WebUtil;
import com.pwa.web.struts.form.ImportMasterDataForm;

public class ImportMasterDataAction extends BaseAction {
	public static Logger log = Logger.getLogger(ImportMasterDataAction.class);

	public ActionForward main(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
			throws UnsupportedEncodingException {
		HttpSession session = request.getSession();
		String type = WebUtil.getURIParam(request, "type");
		log.debug("enter " + type);
		session.setAttribute("type", type);
		return mapping.findForward("main");
	}

	public ActionForward submit(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)
			throws FileNotFoundException, IOException, ParseException {
		HttpSession session = request.getSession();
		ImportMasterDataForm f = (ImportMasterDataForm) form;
		MessageList msgList = new MessageList();
		String type = (String) session.getAttribute("type");
		log.debug("enter " + type);

		// do sysn data
		int rowEffect = 0;
		try {
			
			String tNameStr = ((String[]) WebConst.getInstance().getMasterTypeMap().get(type))[1];
			String[] tNames = tNameStr.split(",");

			for (int i = 0; i < tNames.length; i++) {
				rowEffect += MasterImporter.run(tNames[i]);
			}
			msgList.addMessage("I","ปรับปรุง" +tNameStr+"สำเร็จรวม"+rowEffect+"รายการ");
		} catch (Exception e) {
			msgList.addMessage(e);
			e.printStackTrace();
		}

		ActionForward forward = null;
		if (!msgList.isContainError()) {
			forward = mapping.findForward("success");
		} else {
			forward = mapping.findForward("main");
		}

		saveMessages(request, ScreenMsgUtil.getMsgsToScreen(msgList));
		return forward;
	}
}