/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.action;

import java.util.ArrayList;
import java.util.TreeMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pwa.common.CUtil;
import com.pwa.common.MessageList;
import com.pwa.common.exception.CMException;
import com.pwa.data.DBHelper;
import com.pwa.web.ScreenMsgUtil;
import com.pwa.web.helper.InvoiceHelper;
import com.pwa.web.struts.form.MeterCardForm;
import com.pwa.web.view.InvoiceView;

public class MeterCardAction extends DispatchAction {
	Logger log = Logger.getLogger(MeterCardAction.class);

	public ActionForward main(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		log.debug("enter ");
		return mapping.findForward("main");
	}

	public ActionForward submit(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
		HttpSession session = request.getSession();
		String br = (String)session.getAttribute("br");
		MeterCardForm f = (MeterCardForm) form;
		log.debug("enter ");
		MessageList msgList = new MessageList();

		String custcode = f.getCustcode();
		try {

			if (CUtil.isBlank(custcode)) { // validate
				throw new CMException("E",  "กรุณากรอกชื่อผูใช้" );
			}

			TreeMap c = new TreeMap();
			custcode = CUtil.getNullIfEmpty(custcode);
			DBHelper.putToCriIfNotNull(c, "custcode", custcode);
					
			// get InvoiceView
			ArrayList r = new ArrayList();
			InvoiceView view = InvoiceHelper.getMeterCardView(c,br,r);
			if(view ==null){
				throw new CMException("E","ไม่พบข้อมูลผู้ใช้น้ำ" );
			}
			session.setAttribute("view", view);
			session.setAttribute("viewList", r);
			
		} catch (Exception e) {
			e.printStackTrace();
			msgList.addMessage(e);
		}

		ActionForward forward = null;
		if (!msgList.isContainError()) {
			forward = mapping.findForward("success");
		} else {
			forward = mapping.findForward("main");
		}

		saveMessages(request, ScreenMsgUtil.getMsgsToScreen(msgList));

		return forward;
	}

}