/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.form;


/** 
 * MyEclipse Struts
 * Creation date: 01-14-2552
 * 
 * XDoclet definition:
 * @struts.form name="importMasterDataForm"
 */
public class ConfigForm extends ImportDataForm {
	private String br;
	private String head;
	private String telno;
	private String lowtype1;
	private String lowtype2;
	private String lowtype3;
	private String bankdate;
	private String paydate;

	public String getHead() {
		return head;
	}
	public void setHead(String head) {
		this.head = head;
	}
	public String getTelno() {
		return telno;
	}
	public void setTelno(String telno) {
		this.telno = telno;
	}
	public String getLowtype1() {
		return lowtype1;
	}
	public void setLowtype1(String lowtype1) {
		this.lowtype1 = lowtype1;
	}
	public String getLowtype2() {
		return lowtype2;
	}
	public void setLowtype2(String lowtype2) {
		this.lowtype2 = lowtype2;
	}
	public String getLowtype3() {
		return lowtype3;
	}
	public void setLowtype3(String lowtype3) {
		this.lowtype3 = lowtype3;
	}
	public String getBankdate() {
		return bankdate;
	}
	public void setBankdate(String bankdate) {
		this.bankdate = bankdate;
	}

	public String getBr() {
		return br;
	}
	public void setBr(String br) {
		this.br = br;
	}
	public String getPaydate() {
		return paydate;
	}
	public void setPaydate(String paydate) {
		this.paydate = paydate;
	}
}