/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.form;


/** 
 * MyEclipse Struts
 * Creation date: 01-14-2552
 * 
 * XDoclet definition:
 * @struts.form name="importMasterDataForm"
 */
public class ImportMasterDataForm extends ImportDataForm {
	
}