/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.form;


/** 
 * MyEclipse Struts
 * Creation date: 01-13-2552
 * 
 * XDoclet definition:
 * @struts.form name="reportSummaryForm"
 */
public class ReportSummaryForm extends ReportNormalForm {
	
}