/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

public class ReportNormalForm extends BaseForm {
	
	private String datetoStr;
	private String br;


	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {

		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public void setDatetoStr(String datetoStr) {
		this.datetoStr = datetoStr;
	}

	public String getDatetoStr() {
		return datetoStr;
	}

	/**
	 * @return the br
	 */
	public String getBr() {
		return br;
	}

	/**
	 * @param br the br to set
	 */
	public void setBr(String br) {
		this.br = br;
	}



}