/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pwa.web.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 12-30-2551
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginForm"
 */
public class UserInquiryForm extends BaseForm {

	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {

		return null;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

}